### ISSUE TITLE
Script "convert_model" fails if model contains multiple embedding layers

### ISSUE THREAD

**Issue by hunyadi** [Dobiasd/frugally-deep#123]
When a model contains multiple `Embedding` layers with different `input_dim` parameter values, `convert_model.py` can fail transforming the model from HD5 to JSON. The error is specific to models formulated with the functional API. (Sequential models can only have a single `Embedding` layer.)

In order to test model consistency, `convert_model.py` executes the trained model with various input data. Most layer types can take any real number as input, and random values chosen from a normal distribution with mean and standard deviation of `(0,1)` are perfect as input for such models. However, `Embedding` layers take integers, and the range of accepted integers is `[0,input_dim)`. Currently, `convert_model.py` switches to an integer random variable if the model contains an `Embedding` layer. While this approach is suitable for sequential models, functional API models can have mixed input types where some inputs take real values while others take integer values. The code should trace `Input` layers whether they are wired to regular layers (e.g. `Dense`), in which case real values are acceptable, or to `Embedding` layers, in which case input data values must be in the range `[0,input_dim)` where `input_dim` is the layer-specific `Embedding` parameter value.

Sample exception thrown in the case of a multi-input model that has two `Embedding` layers, one with `input_dim=500` and another with `input_dim=53`:

```
Traceback (most recent call last):
  File "convert_model.py", line 665, in <module>
    main()
  File "convert_model.py", line 661, in main
    convert(in_path, out_path)
  File "convert_model.py", line 616, in convert
    test_data = gen_test_data(model, random_fn)
  File "convert_model.py", line 138, in gen_test_data
    measure_predict(model, data_in)
  File "convert_model.py", line 96, in measure_predict
    data_out = model.predict(data_in)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/training.py", line 1169, in predict
    steps=steps)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/training_arrays.py", line 294, in predict_loop
    batch_outs = f(ins_batch)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0,0] = 463 is not in [0, 53)
	 [[{{node pos_embedding/embedding_lookup}} = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](pos_embedding/embeddings/read, _arg_tags_0_1, pos_embedding/embedding_lookup/axis)]]
```

**Comment by Dobiasd** [comment]
Thanks for the very clear report. I have understood the issue and reproduced it. I'll adjust `convert_model.py` accordingly.

**Comment by Dobiasd** [comment]
@hunyadi Should be OK now. At least my test case that produced the same error is fixed now. Please let me know if any further issues arise.

**Comment by hunyadi** [comment]
Pulling the latest commit from `master`, our model now converts correctly without errors. Thanks for fixing the issue.
