### ISSUE TITLE
convert model failed:  ValueError: Unknown loss function:quad_loss

### ISSUE THREAD

**Issue by globalmaster** [Dobiasd/frugally-deep#131]
Hi,
I'm trying to convert my .h5 model to .json file on Ubuntu16.04 with keras==2.2.4 
tensorflow-gpu==1.12.0.
My .h5 model file can be download here: https://drive.google.com/open?id=1QVQiS4rsCuHFoQw-tarYLw6EqegIzMfD

I get this error:
Traceback (most recent call last):
  File "keras_export/convert_model.py", line 777, in <module>
    main()
  File "keras_export/convert_model.py", line 773, in main
    convert(in_path, out_path)
  File "keras_export/convert_model.py", line 719, in convert
    model = load_model(in_path)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/saving.py", line 312, in _deserialize_model
    sample_weight_mode=sample_weight_mode)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 139, in compile
    loss_function = losses.get(loss)
  File "/usr/local/lib/python3.5/dist-packages/keras/losses.py", line 133, in get
    return deserialize(identifier)
  File "/usr/local/lib/python3.5/dist-packages/keras/losses.py", line 114, in deserialize
    printable_module_name='loss function')
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/generic_utils.py", line 165, in deserialize_keras_object
    ':' + function_name)
ValueError: Unknown loss function:quad_loss

How can I fix this error? Can you help me?

**Comment by Dobiasd** [comment]
The following minimal code raises the same exception:
```python
from keras.models import load_model
load_model('east_model_3T736.h5')
```

So it seems your problem is not caused by frugally-deep.

I guess you are using a custom loss function (`quad_loss`). Try your `save_model` call with `include_optimizer=False` or to remove/replace the loss function by other means before saving. It is not needed for prediction anyways. :)

**Comment by globalmaster** [comment]
> The following minimal code raises the same exception:
> 
> ```python
> from keras.models import load_model
> load_model('east_model_3T736.h5')
> ```
> 
> So it seems your problem is not caused by frugally-deep.
> 
> I guess you are using a custom loss function (`quad_loss`). Try your `save_model` call with `include_optimizer=False` or to remove/replace the loss function by other means before saving. It is not needed for prediction anyways. :)

I'm trying save_model call with include_optimizer=False.
Thank you for your help!
