### ISSUE TITLE
"convert_model.py" fails for Keras model with embedding layers that take multiple inputs

### ISSUE THREAD

**Issue by hunyadi** [Dobiasd/frugally-deep#151]
When trying to convert a _HDF5_ Keras model to a _JSON_ model, `convert_model.py` fails saying it cannot generate test data, suggesting the embedding layers are not positioned after input nodes:
```
$ python3 convert_model.py model.h5 model.json
Using TensorFlow backend.
loading model.h5
2019-07-10 10:32:27.598669: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/saving.py:292: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/sequential.py:110: UserWarning: `Sequential.model` is deprecated. `Sequential` is a subclass of `Model`, you can just use your `Sequential` instance directly.
  warnings.warn('`Sequential.model` is deprecated. '
Traceback (most recent call last):
  File "convert_model.py", line 831, in <module>
    main()
  File "convert_model.py", line 827, in main
    convert(in_path, out_path, no_tests)
  File "convert_model.py", line 800, in convert
    json_output = model_to_fdeep_json(model, no_tests)
  File "convert_model.py", line 750, in model_to_fdeep_json
    test_data = None if no_tests else gen_test_data(model)
  File "convert_model.py", line 197, in gen_test_data
    model), "Test data can only be generated if embedding layers are positioned directly after input nodes."
AssertionError: Test data can only be generated if embedding layers are positioned directly after input nodes.
```

In Keras, embedding layers always have to be first layers or positioned directly after input layers, or the model cannot be trained. The model that triggers the above failure admits the following structure:
```
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
words_behind (InputLayer)       (None, 16)           0                                            
__________________________________________________________________________________________________
tags_behind (InputLayer)        (None, 16)           0                                            
__________________________________________________________________________________________________
words_ahead (InputLayer)        (None, 4)            0                                            
__________________________________________________________________________________________________
tags_ahead (InputLayer)         (None, 4)            0                                            
__________________________________________________________________________________________________
word_embedding (Embedding)      multiple             7936        words_behind[0][0]               
                                                                 words_ahead[0][0]                
__________________________________________________________________________________________________
tag_embedding (Embedding)       multiple             360         tags_behind[0][0]                
                                                                 tags_ahead[0][0]                 
```

Observe that the model has four input layers, two of which are connected to one embedding layer and two of which are connected to another embedding layer. This is perfectly legit in Keras, and the model trains correctly.

**Comment by Dobiasd** [comment]
Thanks for the report. I'll try to reproduce the issue locally with a minimal example, and I'll get back to you with the results.

**Comment by Dobiasd** [comment]
Up to now, I did not succeed to recreate such a model.

My current attempt looks as follows:

```python3
from keras.layers import Input, Embedding
from keras.models import Model

words_behind = Input((16,), name='words_behind')
tags_behind = Input((16,), name='tags_behind')

words_ahead = Input((4,), name='words_ahead')
tags_ahead = Input((4,), name='tags_ahead')

word_embedding = Embedding(input_dim=(16,), output_dim=3)([words_behind, words_ahead])
tag_embedding = Embedding(input_dim=(16,), output_dim=3)([tags_behind, tags_ahead])

model = Model(inputs=[words_behind, words_ahead, tags_behind, tags_ahead],
              outputs=[word_embedding, tag_embedding])
model.compile(loss='mse', optimizer='adam')
model.save("model.h5")
```

However, it fails with the following error (minimized):

```
Traceback (most recent call last):
  ...
    word_embedding = Embedding(input_dim=(16,), output_dim=3)([words_behind, words_ahead])
  ...
ValueError: Argument must be a dense tensor: ((16,), 3) - got shape [2], but wanted [2, 1].
```

Could you help me out here? How do I connect multiple inputs to one embedding layer?

---

In the meantime, in case you are blocked by this issue, you can try to run `convert_model.py` with the `--no-tests` flag. It will skip generating test data, and hopefully produce a `.json` file that you can use in C++. However, of course, `fdeep::load_model` will not run any tests then.

**Comment by Dobiasd** [comment]
OK, I recreated the problem (`AssertionError: Test data can only be generated if embedding layers are positioned directly after input nodes.`) with the following model

```python3
from keras.layers import Input, Embedding
from keras.models import Model

words_behind = Input((16,), name='words_behind')
tags_behind = Input((16,), name='tags_behind')
words_ahead = Input((4,), name='words_ahead')
tags_ahead = Input((4,), name='tags_ahead')

word_embedding = Embedding(input_dim=16, output_dim=3)
tag_embedding = Embedding(input_dim=4, output_dim=3)

words_behind_embedding_output = word_embedding(words_behind)
words_ahead_embedding_output = word_embedding(words_ahead)
tags_behind_embedding_output = tag_embedding(tags_behind)
tags_ahead_embedding_output = tag_embedding(tags_ahead)

model = Model(inputs=[words_behind, words_ahead, tags_behind, tags_ahead],
              outputs=[words_behind_embedding_output, words_ahead_embedding_output,
                       tags_behind_embedding_output, tags_ahead_embedding_output])
model.compile(loss='mse', optimizer='adam')
model.save("model.h5")
```

I will try to found out why it does not work and get back to you then.

---

In the meantime, in case you are blocked by this issue, you can try to run `convert_model.py` with the `--no-tests` flag. It will skip generating test data, and hopefully produce a `.json` file that you can use in C++. However, of course, `fdeep::load_model` will not run any tests then.

**Comment by Dobiasd** [comment]
OK, [fixed it](https://github.com/Dobiasd/frugally-deep/commit/5c05ea2e08b6d27369bbb684e6f4131137b112cd). :heavy_check_mark:

`convert_model.py` is now able to correctly generate a test case for your model. :tada:

Thanks, as usual, for this good bug report, which helped to improve the quality of the library. :slightly_smiling_face:
