### ISSUE TITLE
convert_model.py (Converting model weights ERROR)

### ISSUE THREAD

**Issue by TikhonovAleksey-AI** [Dobiasd/frugally-deep#237]
Hello,
Thank you for sharing your work.

**Unfortunately, when I try to use convert_model.py script, i've got an error.**

`Microsoft Windows [Version 10.0.17763.316]
(c) Корпорация Майкрософт (Microsoft Corporation), 2018. Все права защищены.

D:\>python frugally-deep-master\keras_export\convert_model.py mnist-dense_000.hdf5 json_model_000.json
2020-08-11 22:00:32.331311: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
loading mnist-dense_000.hdf5
WARNING:tensorflow:From C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
2020-08-11 22:00:34.339453: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-08-11 22:00:34.358576: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce GTX 1060 6GB major: 6 minor: 1 memoryClockRate(GHz): 1.7085
pciBusID: 0000:01:00.0
2020-08-11 22:00:34.365556: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-08-11 22:00:34.371857: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-08-11 22:00:34.377394: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-08-11 22:00:34.381787: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-08-11 22:00:34.387961: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-08-11 22:00:34.395042: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-08-11 22:00:34.405680: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-08-11 22:00:34.411806: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-08-11 22:00:34.415704: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-08-11 22:00:34.422875: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce GTX 1060 6GB major: 6 minor: 1 memoryClockRate(GHz): 1.7085
pciBusID: 0000:01:00.0
2020-08-11 22:00:34.429565: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-08-11 22:00:34.434544: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-08-11 22:00:34.439155: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-08-11 22:00:34.443541: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-08-11 22:00:34.447991: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-08-11 22:00:34.452769: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-08-11 22:00:34.456682: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-08-11 22:00:34.461286: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-08-11 22:00:34.962996: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-08-11 22:00:34.967814: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0
2020-08-11 22:00:34.970725: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
2020-08-11 22:00:34.974658: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4708 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
WARNING:tensorflow:From C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\ops\nn_impl.py:183: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
2020-08-11 22:00:40.557618: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-08-11 22:00:40.743252: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-08-11 22:00:41.447754: W tensorflow/stream_executor/cuda/redzone_allocator.cc:312] Internal: Invoking ptxas not supported on Windows
Relying on driver to perform ptx compilation. This message will be only logged once.
2020-08-11 22:00:42.157451: W tensorflow/core/common_runtime/bfc_allocator.cc:239] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.15GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
Forward pass took 1.801435 s.
Forward pass took 0.034907 s.
Forward pass took 0.033933 s.
Starting performance measurements.
Forward pass took 0.035904 s.
Forward pass took 0.033908 s.
Forward pass took 0.033917 s.
Forward pass took 0.034879 s.
Forward pass took 0.034907 s.
Forward pass took 0.034703 s on average.
Converting model architecture.
Converting model weights.
Traceback (most recent call last):
  File "frugally-deep-master\keras_export\convert_model.py", line 817, in <module>
    main()
  File "frugally-deep-master\keras_export\convert_model.py", line 813, in main
    convert(in_path, out_path, no_tests)
  File "frugally-deep-master\keras_export\convert_model.py", line 786, in convert
    json_output = model_to_fdeep_json(model, no_tests)
  File "frugally-deep-master\keras_export\convert_model.py", line 771, in model_to_fdeep_json
    json_output['trainable_params'] = get_all_weights(model)
  File "frugally-deep-master\keras_export\convert_model.py", line 606, in get_all_weights
    result = merge_two_disjunct_dicts(result, get_all_weights(layer))
  File "frugally-deep-master\keras_export\convert_model.py", line 581, in merge_two_disjunct_dicts
    assert set(get_dict_keys(x)).isdisjoint(get_dict_keys(y))
AssertionError`

**My network architecture:**

______________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_7 (InputLayer)            [(None, 256, 256, 3) 0                                            
__________________________________________________________________________________________________
input_8 (InputLayer)            [(None, 256, 256, 3) 0                                            
__________________________________________________________________________________________________
vgg19_1 (Model)                 (None, 8, 8, 512)    20024384    input_7[0][0]                    
__________________________________________________________________________________________________
vgg19_2 (Model)                 (None, 8, 8, 512)    20024384    input_8[0][0]                    
__________________________________________________________________________________________________
concatenate_1 (Concatenate)     (None, 8, 8, 1024)   0           vgg19_1[1][0]                    
                                                                 vgg19_2[1][0]                    
__________________________________________________________________________________________________
flatten_1 (Flatten)             (None, 65536)        0           concatenate_1[0][0]              
__________________________________________________________________________________________________
dense_5 (Dense)                 (None, 512)          33554944    flatten_1[0][0]                  
__________________________________________________________________________________________________
dense_6 (Dense)                 (None, 256)          131328      dense_5[0][0]                    
__________________________________________________________________________________________________
dense_7 (Dense)                 (None, 128)          32896       dense_6[0][0]                    
__________________________________________________________________________________________________
dense_8 (Dense)                 (None, 64)           8256        dense_7[0][0]                    
__________________________________________________________________________________________________
dropout_1 (Dropout)             (None, 64)           0           dense_8[0][0]                    
__________________________________________________________________________________________________
dense_9 (Dense)                 (None, 1)            65          dropout_1[0][0]                  
==================================================================================================
Total params: 73,776,257
Trainable params: 73,698,817
Non-trainable params: 77,440
__________________________________________________________________________________________________
None

Model creation:

`vgg_net_1 = VGG19(weights='imagenet', include_top=False, input_shape=(256, 256, 3))       
vgg_net_2 = VGG19(weights='imagenet', include_top=False, input_shape=(256, 256, 3))    
     
vgg_net_1._name = 'vgg19_1'
vgg_net_2._name = 'vgg19_2'

vgg_net_1.trainable = True
trainable = False
for layer in vgg_net_1.layers:
    if ( (layer.name == 'block2_conv1') or (layer.name == 'block3_conv1') or (layer.name == 'block4_conv1') or (layer.name == 'block5_conv1') ):
        trainable = True
    layer.trainable = trainable
    
    
vgg_net_2.trainable = True
trainable = False
for layer in vgg_net_2.layers:
    if ( (layer.name == 'block2_conv1') or (layer.name == 'block3_conv1') or (layer.name == 'block4_conv1') or (layer.name == 'block5_conv1') ):
        trainable = True
    layer.trainable = trainable

     
     
inputA = Input(shape=input_shape)
inputB = Input(shape=input_shape)  

x = vgg_net_1(inputA)
x = Model(inputs=inputA, outputs=x, name='MyModel_img_1')

y = vgg_net_2(inputB)
y = Model(inputs=inputB, outputs=y, name='MyModel_img_2')

combined = concatenate( [x.output, y.output] )

z = Flatten()(combined)
z = Dense(512, activation='relu')(z)
z = Dense(256, activation='relu')(z)
z = Dense(128, activation='relu')(z)
z = Dense(64, activation='relu')(z)
z = Dropout(0.5)(z)
z = Dense(1, activation='sigmoid')(z)

model = Model(inputs=[x.input, y.input], outputs=z, name='MyModel')`

**If you create the following architecture, then the conversion is successful:**

vgg16_net_1 = VGG16(weights='imagenet', include_top=False, input_shape=(256, 256, 3))       

vgg16_net_1.trainable = True
trainable = False
for layer in vgg16_net_1.layers:
    if layer.name == 'block5_conv1':
        trainable = True
    layer.trainable = trainable
    

inputA = Input(shape=input_shape)
inputB = Input(shape=input_shape)  

x = vgg16_net_1(inputA)
x = Model(inputs=inputA, outputs=x)

y = vgg16_net_1(inputB)           !!!!!!!!!!!!!!!!!!!!!!!!!!
y = Model(inputs=inputB, outputs=y)

combined = concatenate( [x.output, y.output] )

z = Flatten()(combined)
z = Dense(256, activation='relu')(z)
z = Dropout(0.5)(z)
z = Dense(1, activation='sigmoid')(z)

model = Model(inputs=[x.input, y.input], outputs=z)

model.summary()

**My hdf5 file which gives error:**
[https://drive.google.com/file/d/1OeA40Xdr7rQhRAXh8ZAC4lCXzxwk15ZM/view?usp=sharing](url)

**Please help me fix the error if it is possible. Very necessary !!! 
Thanks !!!**

**Comment by Dobiasd** [comment]
> My hdf5 file which gives error:
> https://drive.google.com/file/d/1OeA40Xdr7rQhRAXh8ZAC4lCXzxwk15ZM/view?usp=sharing

You seem to not yet have enabled public access to the file you uploaded, so I requested access on Google Drive. Once I can download it, I'll test.

**Comment by TikhonovAleksey-AI** [comment]
Sorry, 
[https://drive.google.com/file/d/1OeA40Xdr7rQhRAXh8ZAC4lCXzxwk15ZM/view?usp=sharing](url)

**Comment by Dobiasd** [comment]
Thanks. With [this `Dockerfile`](https://gist.github.com/Dobiasd/41564af6001cb71ff51869583ed8df39) your problem is reproduced:

```
[..]
Forward pass took 1.2466418 s on average.
Converting model architecture.
Converting model weights.
Traceback (most recent call last):
  File "./frugally-deep/keras_export/convert_model.py", line 817, in <module>
    main()
  File "./frugally-deep/keras_export/convert_model.py", line 813, in main
    convert(in_path, out_path, no_tests)
  File "./frugally-deep/keras_export/convert_model.py", line 786, in convert
    json_output = model_to_fdeep_json(model, no_tests)
  File "./frugally-deep/keras_export/convert_model.py", line 771, in model_to_fdeep_json
    json_output['trainable_params'] = get_all_weights(model)
  File "./frugally-deep/keras_export/convert_model.py", line 606, in get_all_weights
    result = merge_two_disjunct_dicts(result, get_all_weights(layer))
  File "./frugally-deep/keras_export/convert_model.py", line 581, in merge_two_disjunct_dicts
    assert set(get_dict_keys(x)).isdisjoint(get_dict_keys(y))
AssertionError
```

I'll investigate and get back to you.

**Comment by TikhonovAleksey-AI** [comment]
Thank you very much for the quick answer. I will wait

**Comment by Dobiasd** [comment]
Ah, frugally-deep stores the layer weights in the JSON file by layer name.

Your model is composed of two VGG19 networks, so layer names are not unique.

I never thought of this, but it makes sense for frugally-deep to support this kind of composition. I'll see what I can do.

**Comment by Dobiasd** [comment]
Good news, I think I found a solution. :slightly_smiling_face:

Using the new `prefixed-layer-names` branch of frugally-deep, your model works: https://gist.github.com/Dobiasd/e3f17164529c3ea5e3f81fdf83dc3b99

I'll test a bit more, but I guess I'll merge [the PR](https://github.com/Dobiasd/frugally-deep/pull/239) into master soon and release a new version.

**Comment by Dobiasd** [comment]
@TikhonovAleksey-AI

Your model works with [the new version `v0.15.1-p0`](https://github.com/Dobiasd/frugally-deep/releases/tag/v0.15.1-p0). :tada:

Thanks a lot for reporting this issue. Good reports like that help to improve the overall quality of the library for all its users. :+1:

**Comment by TikhonovAleksey-AI** [comment]
Thank you very much for your contribution to development big data science !!! 
Your library is beautiful.
