### ISSUE TITLE
Error when I tried convert predefined model InceptionV3

### ISSUE THREAD

**Issue by aligoglos** [Dobiasd/frugally-deep#250]
I've tried to convert predefined model InceptionV3 but i got error !
first i tried to save predefined model with below code:

```
import tensorflow.keras as keras
def save_model():
    im = cv2.imread("imgs/im.png").astype('float32')
    base_model = keras.applications.InceptionV3(include_top=False, weights='inception_v3_weights_tf_dim_ordering_tf_kernels_notop.h5')
    img1p1 = np.expand_dims(im, axis=0)
    deepFeature1 =  base_model.predict(img1p1).flatten()
    base_model.save("inception_v3.h5")
```

and then i ran `py convert_model.py  inception_v3.h5 inception_v3.json `
but this error occurred:

```
Traceback (most recent call last):
  File "convert_model.py", line 818, in <module>
    main()
  File "convert_model.py", line 814, in main
    convert(in_path, out_path, no_tests)
  File "convert_model.py", line 787, in convert
    json_output = model_to_fdeep_json(model, no_tests)
  File "convert_model.py", line 759, in model_to_fdeep_json
    test_data = None if no_tests else gen_test_data(model)
  File "convert_model.py", line 184, in gen_test_data
    data_out_test, duration = measure_predict(model, data_in)
  File "convert_model.py", line 104, in measure_predict
    data_out = model.predict(data_in)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\engine\training.py", line 130, in _method_wrapper
    return method(self, *args, **kwargs)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1599, in predict
    tmp_batch_outputs = predict_function(iterator)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\eager\def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\eager\def_function.py", line 823, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\eager\def_function.py", line 697, in _initialize
    *args, **kwds))
  File "C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\eager\function.py", line 2855, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\eager\function.py", line 3213, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\eager\function.py", line 3075, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\eager\def_function.py", line 600, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\func_graph.py", line 973, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\engine\training.py:1462 predict_function  *
        return step_function(self, iterator)
    C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\engine\training.py:1452 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1211 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2585 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2945 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\engine\training.py:1445 run_step  **
        outputs = model.predict_step(data)
    C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\engine\training.py:1418 predict_step
        return self(x, training=False)
    C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:985 __call__
        outputs = call_fn(inputs, *args, **kwargs)
    C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\engine\functional.py:386 call
        inputs, training=training, mask=mask)
    C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\engine\functional.py:508 _run_internal_graph
        outputs = node.layer(*args, **kwargs)
    C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:985 __call__
        outputs = call_fn(inputs, *args, **kwargs)
    C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\layers\convolutional.py:247 call
        outputs = self._convolution_op(inputs, self.kernel)
    C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\util\dispatch.py:201 wrapper
        return target(*args, **kwargs)
    C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\ops\nn_ops.py:1018 convolution_v2
        name=name)
    C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\ops\nn_ops.py:1148 convolution_internal
        name=name)
    C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\ops\nn_ops.py:2592 _conv2d_expanded_batch
        name=name)
    C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py:979 conv2d
        data_format=data_format, dilations=dilations, name=name)
    C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\op_def_library.py:744 _apply_op_helper
        attrs=attr_protos, op_def=op_def)
    C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\func_graph.py:593 _create_op_internal
        compute_device)
    C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\ops.py:3485 _create_op_internal
        op_def=op_def)
    C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\ops.py:1975 __init__
        control_input_ops, op_def)
    C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\ops.py:1815 _create_c_op
        raise ValueError(str(e))

    ValueError: Negative dimension size caused by subtracting 3 from 1 for '{{node inception_v3/conv2d_29/Conv2D}} = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], explicit_paddings=[], padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true](inception_v3/activation_28/Relu, inception_v3/conv2d_29/Conv2D/ReadVariableOp)' with input shapes: [?,1,1,96], [3,3,96,96].
```

I think input dimensions aren't right.

**Comment by Dobiasd** [comment]
Hi,

I'm trying to reproduce your error, but the code fails even earlier:

```python3
import tensorflow
model = tensorflow.keras.applications.InceptionV3(include_top=False, weights='inception_v3_weights_tf_dim_ordering_tf_kernels_notop.h5')
model.save('model.h5')
```

```
  File "main.py", line 2, in <module>
    model = tensorflow.keras.applications.InceptionV3(include_top=False, weights='inception_v3_weights_tf_dim_ordering_tf_kernels_notop.h5')
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/applications/inception_v3.py", line 112, in InceptionV3
    raise ValueError('The `weights` argument should be either '
ValueError: The `weights` argument should be either `None` (random initialization), `imagenet` (pre-training on ImageNet), or the path to the weights file to be loaded.
```

Here is the `Dockerfile` to reproduce this: https://gist.github.com/Dobiasd/cd466519413a0fb8fe8a7a09af189371

Basically, there is no `inception_v3_weights_tf_dim_ordering_tf_kernels_notop.h5` out of the box.

Could you please give me a download link to it?

But first, please make sure you're using the latest version of frugally-deep, TensorFlow 2.3. Also, and this might be especially important, please make sure, you're using `tensorflow.keras.applications...` and not `keras.applications...`. Since you did not show the imports from the code you've posted, I don't know if you have `import keras` or `from tensorflow import keras`. Frugally-deep does not support `keras`. It only supports `tensorflow.keras`.

**Comment by aligoglos** [comment]
I think I downloaded the weights manually but it's same if you set weights to `imagenet`

**Comment by Dobiasd** [comment]
Thanks.

I was able to reproduce the issue with this `Dockerfile`: https://gist.github.com/Dobiasd/2c74b06f072a6ba45893b75f097fb998

Setting an explicit `input_shape` for the model helps: https://gist.github.com/Dobiasd/3f57d499ab2b38c32b1b5f2a195d6b30

Is this a feasuble solution for you?

**Comment by aligoglos** [comment]
Yes the solution works.
thanks.
