### ISSUE TITLE
incompatibility of shape

### ISSUE THREAD

**Issue by sara-hoseininasab** [Dobiasd/frugally-deep#256]
Hello,
I want to convert a Keras model to JSON using frugally-deep:
input layer shape: (100,128,3)
input layer data type: 'float32'

and I use tensorflow 2.3.1 . 
I get the error when I use the below command for converting the model to json file:
`python convert_model.py model.h5 model.json`

error:
```
Traceback (most recent call last):
  File "../../../../../frugally-deep/keras_export/convert_model.py", line 818, in <module>
    main()
  File "../../../../../frugally-deep/keras_export/convert_model.py", line 814, in main
    convert(in_path, out_path, no_tests)
  File "../../../../../frugally-deep/keras_export/convert_model.py", line 787, in convert
    json_output = model_to_fdeep_json(model, no_tests)
  File "../../../../../frugally-deep/keras_export/convert_model.py", line 759, in model_to_fdeep_json
    test_data = None if no_tests else gen_test_data(model)
  File "../../../../../frugally-deep/keras_export/convert_model.py", line 184, in gen_test_data
    data_out_test, duration = measure_predict(model, data_in)
  File "../../../../../frugally-deep/keras_export/convert_model.py", line 104, in measure_predict
    data_out = model.predict(data_in)
  File "/home/sara/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 130, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/sara/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1599, in predict
    tmp_batch_outputs = predict_function(iterator)
  File "/home/sara/.local/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/home/sara/.local/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 846, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "/home/sara/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/home/sara/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/sara/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/home/sara/.local/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError:    Specified a list with shape [100,3] from a tensor with shape [32,3]
	 [[{{node TensorArrayUnstack/TensorListFromTensor}}]]
	 [[functional_1/lstm/PartitionedCall]] [Op:__inference_predict_function_1055]

Function call stack:
predict_function -> predict_function -> predict_function

```
ps: I use the latest version of frugally-deep.

Thanks in advance

**Comment by Dobiasd** [comment]
Hi,

thanks for the clear report.

Could you upload the h5-model file, such that I can try to reproduce and debug the problem locally?

**Comment by sara-hoseininasab** [comment]
> Hi,
> 
> thanks for the clear report.
> 
> Could you upload the h5-model file, such that I can try to reproduce and debug the problem locally?

Hi,
My h5-model is attached.

Thanks.
[digits.h5.tar.gz](https://github.com/Dobiasd/frugally-deep/files/5610475/digits.h5.tar.gz)

**Comment by Dobiasd** [comment]
Thanks. I was able to reproduce the issue:

```Dockerfile
FROM python:3.7

RUN apt-get update
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get install -y build-essential cmake

RUN pip3 install tensorflow==2.3.0

RUN git clone -b 'v0.2.9-p0' --single-branch --depth 1 https://github.com/Dobiasd/FunctionalPlus && cd FunctionalPlus && mkdir -p build && cd build && cmake .. && make && make install
RUN git clone -b '3.3.7' --single-branch --depth 1 https://github.com/eigenteam/eigen-git-mirror && cd eigen-git-mirror && mkdir -p build && cd build && cmake .. && make && make install && ln -s /usr/local/include/eigen3/Eigen /usr/local/include/Eigen
RUN git clone -b 'v3.7.3' --single-branch --depth 1 https://github.com/nlohmann/json && cd json && mkdir -p build && cd build && cmake -DBUILD_TESTING=OFF .. && make && make install
RUN git clone --depth 1 https://github.com/Dobiasd/frugally-deep && cd frugally-deep && mkdir -p build && cd build && cmake .. && make && make install

RUN wget https://github.com/Dobiasd/frugally-deep/files/5610475/digits.h5.tar.gz
RUN tar -zxvf digits.h5.tar.gz

RUN python3 ./frugally-deep/keras_export/convert_model.py digits.h5 digits.json
```

Error:

```
tensorflow.python.framework.errors_impl.InvalidArgumentError:    Specified a list with shape [100,3] from a tensor with shape [32,3]
```

I'll investigate and get back to you.

**Comment by Dobiasd** [comment]
Turns out, the plumbing of the model is simply invalid regarding the tensor shapes.

```python3
import numpy as np
from tensorflow.keras.models import load_model

model = load_model("digits.h5")
model.summary()
```

```
Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         [(100, 128, 3)]           0         
_________________________________________________________________
lstm (LSTM)                  (100, 128)                67584     
_________________________________________________________________
dense (Dense)                (100, 6)                  774       
=================================================================
Total params: 68,358
Trainable params: 68,358
Non-trainable params: 0
```

`input_1` and `lstm` don't fit.

To confirm this (without using frugally-deep at all):

```python3
print(f"Number of input layers: {len(model._input_layers)}")
in_shape = model._input_layers[0].input_shape
print(f"Input shape: {in_shape}")
in_data = np.random.rand(100, 128, 3)
out_data = model.predict(in_data)
```

```
Number of input layers: 1
Input shape: [(100, 128, 3)]

[...]

tensorflow.python.framework.errors_impl.InvalidArgumentError:    Specified a list with shape [100,3] from a tensor with shape [32,3]
```

So I suspect you never did any successful training of prediction with this model.

**Comment by sara-hoseininasab** [comment]
> Turns out, the plumbing of the model is simply invalid regarding the tensor shapes.
> 
> ```python
> import numpy as np
> from tensorflow.keras.models import load_model
> 
> model = load_model("digits.h5")
> model.summary()
> ```
> 
> ```
> Model: "functional_1"
> _________________________________________________________________
> Layer (type)                 Output Shape              Param #   
> =================================================================
> input_1 (InputLayer)         [(100, 128, 3)]           0         
> _________________________________________________________________
> lstm (LSTM)                  (100, 128)                67584     
> _________________________________________________________________
> dense (Dense)                (100, 6)                  774       
> =================================================================
> Total params: 68,358
> Trainable params: 68,358
> Non-trainable params: 0
> ```
> 
> `input_1` and `lstm` don't fit.
> 
> To confirm this (without using frugally-deep at all):
> 
> ```python
> print(f"Number of input layers: {len(model._input_layers)}")
> in_shape = model._input_layers[0].input_shape
> print(f"Input shape: {in_shape}")
> in_data = np.random.rand(100, 128, 3)
> out_data = model.predict(in_data)
> ```
> 
> ```
> Number of input layers: 1
> Input shape: [(100, 128, 3)]
> 
> [...]
> 
> tensorflow.python.framework.errors_impl.InvalidArgumentError:    Specified a list with shape [100,3] from a tensor with shape [32,3]
> ```
> 
> So I suspect you never did any successful training of prediction with this model.

Thank you so much.
I'll investigate it.
