### ISSUE TITLE
An error in converting Conv1D model

### ISSUE THREAD

**Issue by zhangzhishan** [Dobiasd/frugally-deep#3]
I got an error when converting_model`python3 keras_export/convert_model.py mymodel.h5  fdeep_model.json`
```
Traceback (most recent call last):
  File "keras_export/convert_model.py", line 389, in <module>
    main()
  File "keras_export/convert_model.py", line 367, in main
    check_operation_offset(depth, offset_sep_conv2d_eval, 'valid')
  File "keras_export/convert_model.py", line 327, in check_operation_offset
    output = eval_f(depth, padding, input_data)
  File "keras_export/convert_model.py", line 306, in offset_sep_conv2d_eval
    pointwise_kernel, strides=(3, 3), padding=padding)
  File "/usr/local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 3230, in separable_conv2d
    rate=dilation_rate)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/nn_impl.py", line 486, in separable_conv2d
    channel_multiplier * in_channels, out_channels))
ValueError: Refusing to perform an overparameterized separable convolution: channel_multiplier * in_channels = 1 * 2 = 2 > 1 = out_channels
```

The model architecture is 
```
    model = Sequential()
    model.add(Conv1D(filters,
                    kernel_size,
                    padding='valid',
                    activation='relu',
                    input_shape=(length_data, 1),
                    strides=1))
    model.add(MaxPooling1D())

    model.add(Conv1D(128, 3))
    model.add(Conv1D(128, 3))
    model.add(Activation('relu'))
    model.add(Dropout(0.5))
    model.add(MaxPooling1D())

    model.add(Conv1D(128, 3))
    model.add(Conv1D(128, 3))
    model.add(Activation('relu'))
    model.add(Dropout(0.5))
    model.add(MaxPooling1D())

    model.add(Conv1D(128, 3))
    model.add(Conv1D(128, 3))
    model.add(Activation('relu'))
    model.add(Dropout(0.5))
    model.add(MaxPooling1D())
    model.add(Conv1D(128, 3))
    model.add(Conv1D(128, 3))
    model.add(Activation('relu'))
    model.add(Dropout(0.5))
    model.add(MaxPooling1D())
    model.add(Conv1D(128, 3))
    model.add(Conv1D(128, 3))
    model.add(Activation('relu'))
    model.add(Dropout(0.5))
    model.add(MaxPooling1D())

    model.add(Conv1D(128, 3))
    model.add(Conv1D(128, 3))
    model.add(Activation('relu'))
    model.add(Dropout(0.5))
    model.add(GlobalMaxPooling1D())

    model.add(Dense(hidden_dims))
    model.add(Dropout(0.5))
    model.add(Activation('relu'))

    model.add(Dense(nb_class))
    model.add(Activation('softmax'))

    model.compile(loss='categorical_crossentropy',
                optimizer='adadelta',
                metrics=['accuracy'])

    model.fit(x_train, y_train,
            batch_size=batch_size,
            epochs=epochs,
            validation_data=(x_val, y_val))
```

**Comment by Dobiasd** [comment]
Could you please provide the values to the following variables you are using?

`hidden_dims`, `kernel_size`, `length_data`, `hidden_dims`, `nb_class`

**Comment by Dobiasd** [comment]
Since you did not mention the values for `filters`, `hidden_dims`, `kernel_size`, `length_data` and `nb_class`, I tested the conversion of your model with some dummy values. It worked without error, see below.

```python
# test_1d.py
import numpy as np

from keras.models import Sequential
from keras.layers import Conv1D, MaxPooling1D, Dense, Dropout, Activation, GlobalMaxPooling1D

filters = 16
hidden_dims = 20
kernel_size = 3
length_data = 1024
nb_class = 4

model = Sequential()
model.add(Conv1D(filters,
                kernel_size,
                padding='valid',
                activation='relu',
                input_shape=(length_data, 1),
                strides=1))
model.add(MaxPooling1D())

model.add(Conv1D(128, 3))
model.add(Conv1D(128, 3))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(MaxPooling1D())

model.add(Conv1D(128, 3))
model.add(Conv1D(128, 3))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(MaxPooling1D())

model.add(Conv1D(128, 3))
model.add(Conv1D(128, 3))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(MaxPooling1D())
model.add(Conv1D(128, 3))
model.add(Conv1D(128, 3))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(MaxPooling1D())
model.add(Conv1D(128, 3))
model.add(Conv1D(128, 3))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(MaxPooling1D())

model.add(Conv1D(128, 3))
model.add(Conv1D(128, 3))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(GlobalMaxPooling1D())

model.add(Dense(hidden_dims))
model.add(Dropout(0.5))
model.add(Activation('relu'))

model.add(Dense(nb_class))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy',
            optimizer='adadelta',
            metrics=['accuracy'])

# fit to dummy data
training_data_size = 1
x_train = [np.random.random(size=(training_data_size, length_data, 1))]
y_train = [np.random.random(size=(training_data_size, nb_class))]

model.fit(x_train, y_train, epochs=2)

model.save('test_1d.h5')
```

```
$ python3 test_1d.py
Using TensorFlow backend.
Epoch 1/2
1/1 [==============================] - 3s 3s/step - loss: 3.1009 - acc: 0.0000e+00
Epoch 2/2
1/1 [==============================] - 0s 71ms/step - loss: 5.5243 - acc: 0.0000e+00
```

```$ python3 keras_export/convert_model.py test_1d.h5 test_1d.json
Using TensorFlow backend.
loading test_1d.h5
Forward pass took 0.096933 s.
writing test_1d.json
```

Could you please provide a full example to reproduce the problem. Also try updating to the latest versions of Keras and Tensorflow if possible.

**Comment by zhangzhishan** [comment]
I have updated the Keras and TensorFlow. It can convert successfully. Thank you!
My old version of Keras is `2.0.6`, and tensorflow is `1.2.1`.
