### ISSUE TITLE
GRU in model leads to error: Fail to find the dnn implementation

### ISSUE THREAD

**Issue by noe** [Dobiasd/frugally-deep#317]
I get the following error when trying to convert a model with a GRU layer:

```
Traceback (most recent call last):
  File "frugally-deep/keras_export/convert_model.py", line 839, in <module>
    main()
  File "frugally-deep/keras_export/convert_model.py", line 835, in main
    convert(in_path, out_path, no_tests)
  File "frugally-deep/keras_export/convert_model.py", line 808, in convert
    json_output = model_to_fdeep_json(model, no_tests)
  File "frugally-deep/keras_export/convert_model.py", line 780, in model_to_fdeep_json
    test_data = None if no_tests else gen_test_data(model)
  File "frugally-deep/keras_export/convert_model.py", line 188, in gen_test_data
    data_out_test, duration = measure_predict(model, data_in)
  File "frugally-deep/keras_export/convert_model.py", line 108, in measure_predict
    data_out = model.predict(data_in)
  File "/home/noe/devel/wsd/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/noe/devel/wsd/venv/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnknownError: Graph execution error:

Fail to find the dnn implementation.
         [[{{node CudnnRNN}}]]
         [[sequential/gru/PartitionedCall]] [Op:__inference_predict_function_1331]
```

Any GRU seems to trigger the error, e.g.:

```Python
import keras

model = keras.Sequential()
model.add(keras.layers.Embedding(input_dim=100, output_dim=64))
model.add(keras.layers.GRU(128))
model.add(keras.layers.Dense(10))

model.save('problem_cudnn_model.h5', include_optimizer=False)
```

I am using the master branch of frugally-deep with `tensorflow-gpu==2.8.0`, `keras==2.8.0`, CUDA 11.0.228, cuDNN 8.1.1, on Ubuntu 20.04.2.

Googling around, I found similar problems (see [this](https://github.com/keras-team/keras/issues/10634), [this](https://github.com/tensorflow/tensorflow/issues/36508)). The solution proposed there worked here too: I added these lines at the top of the `convert_model.py` file:

```Python
import tensorflow as tf
for gpu in tf.config.experimental.list_physical_devices('GPU'):
    tf.config.experimental.set_memory_growth(gpu, True)
```

From the bug reports I linked above, this seems like an eigenbug that only happens on some setups. Maybe it would be possible to add the likes of the fix to `convert_model.py`, either in the main path or with a command line option (e.g. `--fix-cudnn-problem`).

And thanks a lot for this great project!

**Comment by noe** [comment]
Sure, I opened a PR with the workaround.

I confirm that `CUDA_VISIBLE_DEVICES=''` also fixes the issue.

As a side note, if you want to use CUDA inside docker, you can use the [nvidia-docker runtime](https://github.com/NVIDIA/nvidia-docker).
