### ISSUE TITLE
assert layer.data_format == 'channels_last' Error

### ISSUE THREAD

**Issue by aligoglos** [Dobiasd/frugally-deep#63]
i trained model with this definition :

```
model_vgg = Sequential()
    model_vgg.add(Conv2D(128, 9, strides=(1, 1), input_shape=inputShape,
                         data_format='channels_last', activation='relu', name='conv1_1'))
    model_vgg.add(MaxPooling2D(pool_size=(2, 2), strides=(1, 1),data_format='channels_last'))
    model_vgg.add(Conv2D(256, 7, strides=(1, 1), activation='relu', name='conv2_1',data_format='channels_last'))
name='conv2_2'),data_format='channels_last')
    model_vgg.add(MaxPooling2D(pool_size=(2, 2), strides=(1, 1),data_format='channels_last'))
    model_vgg.add(Conv2D(256, 5, strides=(1, 1), activation='relu', name='conv3_1',data_format='channels_last'))
    model_vgg.add(MaxPooling2D(pool_size=(2, 2), strides=(1, 1),data_format='channels_last'))
    model_vgg.add(Conv2D(256, 3, strides=(1, 1), activation='relu', name='conv4_1',data_format='channels_last'))
    model_vgg.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2),data_format='channels_last'))
    model_vgg.add(Flatten())
    model_vgg.add(Dense(256, activation='relu'))
    model_vgg.add(Dropout(0.5))
    model_vgg.add(Dense(2, activation='softmax'))
```
but when i want convert model with script `convert_model.py` this error occur :
```
C:\Users\127051\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\engine\sequential.py:109: UserWarning: `Sequential.model` is deprecated. `Sequential` is a subclass of `Model`, you can just use your `Sequential` instance directly.
  warnings.warn('`Sequential.model` is deprecated. '
Forward pass took 0.988684 s.
Forward pass took 0.006995 s.
Forward pass took 0.007967 s.
Starting performance measurements.
Forward pass took 0.007939 s.
Forward pass took 0.007978 s.
Forward pass took 0.007952 s.
Forward pass took 0.007986 s.
Forward pass took 0.007979 s.
Forward pass took 0.0079668 s on average.
Traceback (most recent call last):
  File "convert_model.py", line 540, in <module>
    main()
  File "convert_model.py", line 536, in main
    convert(in_path, out_path)
  File "convert_model.py", line 517, in convert
    json_output['trainable_params'] = get_all_weights(model)
  File "convert_model.py", line 358, in get_all_weights
    assert layer.data_format == 'channels_last'
AssertionError

```

**Comment by Dobiasd** [comment]
Usually you don't need to explicitly set `data_format='channels_last'` for each layer, because it's already the default parameter.

Also `K.image_data_format() == 'channels_last'` seems to be the case with your setup, because otherwise this assertion in `convert_model.py` would have triggered before.

1) Are you using Theano or CNTK as backend instead of TensorFlow? Frugally-deep only supports the latter.

2) What versions of Keras and TensorFlow do you have installed?

3) Are you using the latest version of frugally-deep?

**Comment by aligoglos** [comment]
I use TensorFlow as backend  and keras version is 2.2 and tensorflow is 1.8 and i download latest frugally-deep.

**Comment by Dobiasd** [comment]
Can you please post the actual source of your model definition?

The code you posted is broken (invalid Python):

```python
model_vgg = Sequential()
    model_vgg.add(Conv2D(128, 9, strides=(1, 1), input_shape=inputShape,
                         data_format='channels_last', activation='relu', name='conv1_1'))
    model_vgg.add(MaxPooling2D(pool_size=(2, 2), strides=(1, 1),data_format='channels_last'))
    model_vgg.add(Conv2D(256, 7, strides=(1, 1), activation='relu', name='conv2_1',data_format='channels_last'))
name='conv2_2'),data_format='channels_last')
    model_vgg.add(MaxPooling2D(pool_size=(2, 2), strides=(1, 1),data_format='channels_last'))
    model_vgg.add(Conv2D(256, 5, strides=(1, 1), activation='relu', name='conv3_1',data_format='channels_last'))
    model_vgg.add(MaxPooling2D(pool_size=(2, 2), strides=(1, 1),data_format='channels_last'))
    model_vgg.add(Conv2D(256, 3, strides=(1, 1), activation='relu', name='conv4_1',data_format='channels_last'))
    model_vgg.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2),data_format='channels_last'))
    model_vgg.add(Flatten())
    model_vgg.add(Dense(256, activation='relu'))
    model_vgg.add(Dropout(0.5))
    model_vgg.add(Dense(2, activation='softmax'))
```

**Comment by Dobiasd** [comment]
OK, so the actual minimal code ([reference 1](http://sscce.org), [reference 2](https://stackoverflow.com/help/mcve) :wink:) to reproduce your model is the following:

```python
# fdeep_issue63.py

import keras.optimizers as optimizers
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPooling2D

inputShape = (32, 32, 1)

model_vgg = Sequential()
model_vgg.add(Conv2D(128, 9, strides=(1, 1), input_shape=inputShape, data_format='channels_last', activation='relu', name='conv1_1'))
model_vgg.add(MaxPooling2D(pool_size=(2, 2), strides=(1, 1), data_format='channels_last'))
model_vgg.add(Conv2D(256, 7, strides=(1, 1), activation='relu', name='conv2_1', data_format='channels_last'))
model_vgg.add(MaxPooling2D(pool_size=(2, 2), strides=(1, 1), data_format='channels_last'))
model_vgg.add(Conv2D(256, 5, strides=(1, 1), activation='relu', name='conv3_1', data_format='channels_last'))
model_vgg.add(MaxPooling2D(pool_size=(2, 2), strides=(1, 1), data_format='channels_last'))
model_vgg.add(Conv2D(256, 3, strides=(1, 1), activation='relu', name='conv4_1', data_format='channels_last'))
model_vgg.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2), data_format='channels_last'))
model_vgg.add(Flatten())
model_vgg.add(Dense(256, activation='relu'))
model_vgg.add(Dropout(0.5))
model_vgg.add(Dense(2, activation='softmax'))

sgd = optimizers.SGD(lr=0.001, decay=1e-6, momentum=0.9, nesterov=True)
model_vgg.compile(loss='mse', optimizer=sgd, metrics=['accuracy'])

model_vgg.save('model_vgg.h5', include_optimizer=False)
```

I run it like this:
```
python3 fdeep_issue63.py
```

and convert the model as follows:
```
python3 convert_model.py model_vgg.h5 model_vgg.json
```

It converted without any error and produced a `model_vgg.json` file.

Can you please check if these exact same steps (with the exact same code) really reproduce the problem on your machine? If so, we should check if you are working with any non-default system settings.

**Comment by aligoglos** [comment]
i upload my model :
[my model](https://drive.google.com/open?id=1z1QjKp9CEHdEtrr-3sDzybfJbJHD-Mbq)

**Comment by Dobiasd** [comment]
Is this the file produced by executing the [code I posted](https://github.com/Dobiasd/frugally-deep/issues/63#issuecomment-400683056) on your machine?

**Comment by aligoglos** [comment]
this is model of [This Code](https://github.com/Dobiasd/frugally-deep/issues/63#issuecomment-400604234) i trained in my machine

**Comment by Dobiasd** [comment]
Again, this is no complete code to produce the model. One can not simply paste it into a `.py` file and run it. That is why I created an [actual minimal example code](https://github.com/Dobiasd/frugally-deep/issues/63#issuecomment-400683056) and asked you run it.

Anyways, to keep things short, please use `data_format='channels_last'` for your `Flatten` layer too, i.e.:

```python
model_vgg.add(Flatten(data_format='channels_last'))
```

This should help.

Some settings on your system seem to default to `channels_first` by default. So you either can always set `channels_last` explicitly every time or find this setting and change it, or try to re-install the libraries freshly without adopting the old config files.

**Comment by aligoglos** [comment]
this issue solved with :`
```
from keras import backend as K
K.set_image_data_format('channels_last')
```
